### ISSUE TITLE
Aliases for point redeems/nominations

### ISSUE THREAD

**Issue by PsycloneTM** [gempir/gempbot#57]
A way to add the alias for the emote you redeemed. As well as a way for mods to moderate it if they don't like the alias name.

**Comment by gempir** [comment]
I've decided against this. Mods are free to alias the emote after the emote was added to the channel (both for redeems and elections)

Adding aliasing to the bot would require a lot of extra stuff and logic. The usecase is too narrow.

Also invites more troll nominations/redeems because they quickly redeem common words etc requiring more moderation.
